In [28]:
import pandas as pd
import numpy as np
from  sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

In [11]:
train = pd.read_csv("abalone_train.csv",index_col = 0)
train

Sex  Length  Diameter  Height  Whole weight  Whole weight.1  \
id                                                                  
0       F   0.550     0.430   0.150        0.7715          0.3285   
1       F   0.630     0.490   0.145        1.1300          0.4580   
2       I   0.160     0.110   0.025        0.0210          0.0055   
3       M   0.595     0.475   0.150        0.9145          0.3755   
4       I   0.555     0.425   0.130        0.7820          0.3695   
...    ..     ...       ...     ...           ...             ...   
90610   M   0.335     0.235   0.075        0.1585          0.0685   
90611   M   0.555     0.425   0.150        0.8790          0.3865   
90612   I   0.435     0.330   0.095        0.3215          0.1510   
90613   I   0.345     0.270   0.075        0.2000          0.0980   
90614   I   0.425     0.325   0.100        0.3455          0.1525   

       Whole weight.2  Shell weight  Rings  
id                                          
0              0.1465        0.2400     11  
1              0.2765        0.3200     11  
2              0.0030        0.0050      6  
3              0.2055        0.2500     10  
4              0.1600        0.1975      9  
...               ...           ...    ...  
90610          0.0370        0.0450      6  
90611          0.1815        0.2400      9  
90612          0.0785        0.0815      6  
90613          0.0490        0.0700      6  
90614          0.0785        0.1050      8  

[90615 rows x 9 columns]

In [12]:
testdf = pd.read_csv("abalone_test.csv",index_col = 0)


In [5]:
train["Rings"].unique()

array([11,  6, 10,  9,  4,  8, 15,  7, 12, 20, 17, 13, 14,  5, 23,  3, 22,
       16, 18, 19, 21, 25,  1, 29,  2, 27, 24, 26], dtype=int64)

In [9]:
# as our y is multi-class col == use le;

le =LabelEncoder()
y = le.fit_transform(train["Rings"])
y

array([10, 10,  5, ...,  5,  5,  7], dtype=int64)

In [17]:
# define X:
# as we can see "sex" col == > catergorical data ==> convert into numerical

X = train.drop(["Rings"],axis = 1)
# crete dumies:
dum_X = pd.get_dummies(X,drop_first = True)   
dum_X 

Length  Diameter  Height  Whole weight  Whole weight.1  Whole weight.2  \
id                                                                              
0       0.550     0.430   0.150        0.7715          0.3285          0.1465   
1       0.630     0.490   0.145        1.1300          0.4580          0.2765   
2       0.160     0.110   0.025        0.0210          0.0055          0.0030   
3       0.595     0.475   0.150        0.9145          0.3755          0.2055   
4       0.555     0.425   0.130        0.7820          0.3695          0.1600   
...       ...       ...     ...           ...             ...             ...   
90610   0.335     0.235   0.075        0.1585          0.0685          0.0370   
90611   0.555     0.425   0.150        0.8790          0.3865          0.1815   
90612   0.435     0.330   0.095        0.3215          0.1510          0.0785   
90613   0.345     0.270   0.075        0.2000          0.0980          0.0490   
90614   0.425     0.325   0.100        0.3455          0.1525          0.0785   

       Shell weight  Sex_I  Sex_M  
id                                 
0            0.2400  False  False  
1            0.3200  False  False  
2            0.0050   True  False  
3            0.2500  False   True  
4            0.1975   True  False  
...             ...    ...    ...  
90610        0.0450  False   True  
90611        0.2400  False   True  
90612        0.0815   True  False  
90613        0.0700   True  False  
90614        0.1050   True  False  

[90615 rows x 9 columns]

In [18]:
###################################### Apply Logistic regression #####################################################

In [21]:
lr =  LogisticRegression()

In [30]:
kfold = StratifiedKFold(n_splits = 5, shuffle = True, random_state=24)
params = ({"C":np.linspace(0.001,10,10)})

# define gcv:
gcv = GridSearchCV(lr, param_grid = params, cv = kfold, scoring = "neg_mean_squared_log_error")
gcv.fit(dum_X, y)

print(gcv.best_score_)
print(gcv.best_params_)

C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

-0.04102466318837222
{'C': 10.0}


C:\Users\Rohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [31]:
# create dummies for test set

dum_tst = pd.get_dummies(testdf, drop_first = True)

# find y_pred

y_pred = gcv.predict(dum_tst)
print(y_pred)

[ 8  8  8 ...  9 10  7]


In [35]:
res = pd.DataFrame({"id": list(testdf.index), "rings":y_pred })
res

id  rings
0       90615      8
1       90616      8
2       90617      8
3       90618      8
4       90619      6
...       ...    ...
60406  151021      5
60407  151022      8
60408  151023      9
60409  151024     10
60410  151025      7

[60411 rows x 2 columns]

In [36]:

res.to_csv("sbt_abalone_1.csv",index = False)